### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [JorgeLuisValenzuelaBustos/ISII-WORKSHOPS-Manejo_de_Bodega#4]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by JorgeLuisValenzuelaBustos** [comment]
@Josue-Caballero @MelinaMacias, the issue has been categorized to continue to the next steps

**Comment by JorgeLuisValenzuelaBustos** [comment]
We will proceed to process the request, @Josue-Caballero will be the assigned analyst and will develop the solution, @MelinaMacias will perform the tests.

**Comment by Josue-Caballero** [comment]
@jose598 Added the [analysis document](https://github.com/JorgeLuisValenzuelaBustos/ISII-WORKSHOPS-Manejo_de_Bodega/files/7907243/CostAnalysis.pdf) to be checked.

**Comment by jose598** [comment]
Why so expensive adding just two rules? I don't want to waste a lot of money on this. 
Even I would like to take a look one table with all cases/rules applied for getting the insurance cost result.

**Comment by Josue-Caballero** [comment]
Good afternoon dear customer @jose598,

I apologize on behalf of the development team. The costs sent in the first stay are not correct. All development is covered by the prior contract. The cost of the test specialist was $30 but due to our mistake we reduced his cost to $20. I attach the [updated document](https://github.com/JorgeLuisValenzuelaBustos/ISII-WORKSHOPS-Manejo_de_Bodega/files/7908899/CostAnalysis.pdf), again I stress my most sincere apologies for the error.

**Comment by jose598** [comment]
Ok, you can start working on it.

**Comment by Josue-Caballero** [comment]
The solution for the new requirements has been completed:
 [Rule one](https://github.com/JorgeLuisValenzuelaBustos/ISII-WORKSHOPS-Manejo_de_Bodega/blob/7d186ddd35eedc569c08b10dae11b2e0a1ddec39/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L65) and [Rule 2](https://github.com/JorgeLuisValenzuelaBustos/ISII-WORKSHOPS-Manejo_de_Bodega/blob/7d186ddd35eedc569c08b10dae11b2e0a1ddec39/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L69). @MelinaMacias

**Comment by MelinaMacias** [comment]
The tests of the new rules have been carried out and all have finished successfully
![image](https://user-images.githubusercontent.com/66958015/150451078-543f926d-69a6-4c00-a8ea-a625e8e65d67.png)

**Comment by MelinaMacias** [comment]
Dear customer @jose598,
I attach the document with the generated acceptance tests, which after testing them work correctly.
We look forward to your acceptance.

[TestsPlans.pdf](https://github.com/JorgeLuisValenzuelaBustos/ISII-WORKSHOPS-Manejo_de_Bodega/files/7909953/TestsPlans.pdf)

**Comment by jose598** [comment]
@MelinaMacias Thank you. 
I approved your changes and everything is OK. 

Thank you, please close the issue.

**Comment by JorgeLuisValenzuelaBustos** [comment]
Since @jose598 has completed the verification, @Josue-Caballero  proceed to deploy the app

**Comment by Josue-Caballero** [comment]
@JorgeLuisValenzuelaBustos @jose598 [Solution deployed!](https://github.com/JorgeLuisValenzuelaBustos/ISII-WORKSHOPS-Manejo_de_Bodega/pull/5)

**Comment by JorgeLuisValenzuelaBustos** [comment]
The requirements of the client have been completed and the validation has been obtained.
